// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5qUxbSlh8HzYJGglG3eImRf7dlVQpKw',
    appId: '1:827546226598:web:46a4d749926e14f1ec0967',
    messagingSenderId: '827546226598',
    projectId: 'testing-cli-eb406',
    authDomain: 'testing-cli-eb406.firebaseapp.com',
    storageBucket: 'testing-cli-eb406.appspot.com',
    measurementId: 'G-8F2QNN92DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfJ3BIcp9B2RKbTwb_ltxyUZF9liQ_8M',
    appId: '1:827546226598:android:84649c5a6a3409d1ec0967',
    messagingSenderId: '827546226598',
    projectId: 'testing-cli-eb406',
    storageBucket: 'testing-cli-eb406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghTYUpd8mu-UBycc0xj-1bduwD-9TZaE',
    appId: '1:827546226598:ios:5851cfa7ad6684c3ec0967',
    messagingSenderId: '827546226598',
    projectId: 'testing-cli-eb406',
    storageBucket: 'testing-cli-eb406.appspot.com',
    iosBundleId: 'com.kapoor.fbinit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghTYUpd8mu-UBycc0xj-1bduwD-9TZaE',
    appId: '1:827546226598:ios:9528b81b02caa112ec0967',
    messagingSenderId: '827546226598',
    projectId: 'testing-cli-eb406',
    storageBucket: 'testing-cli-eb406.appspot.com',
    iosBundleId: 'com.kapoor.fbinit.RunnerTests',
  );
}
